# Generated by Django 3.0.5 on 2020-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_name', models.CharField(max_length=32)),
                ('dp_size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('dp_price', models.DecimalField(decimal_places=2, help_text='price in US$', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pastas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta_name', models.CharField(max_length=16)),
                ('pasta_price', models.DecimalField(decimal_places=2, help_text='pice in US$', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad_name', models.CharField(max_length=16)),
                ('salad_price', models.DecimalField(decimal_places=2, help_text='pice in US$', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_name', models.CharField(max_length=32)),
                ('subs_size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('subs_price', models.DecimalField(decimal_places=2, help_text='pice in US$', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Topings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toping_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=16)),
                ('pizza_type', models.CharField(choices=[('S', 'Sicilian'), ('R', 'Regular')], max_length=1)),
                ('pizza_price', models.DecimalField(decimal_places=2, help_text='price in US$', max_digits=5)),
                ('pizza_topings', models.ManyToManyField(blank=True, related_name='topings', to='orders.Topings')),
            ],
        ),
    ]
