# Generated by Django 3.0.5 on 2020-04-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastas',
            name='pasta_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='salads',
            name='salad_name',
            field=models.CharField(max_length=32),
        ),
    ]
