# Generated by Django 3.0.5 on 2020-04-21 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200421_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_topings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default=datetime.datetime(2020, 4, 21, 14, 33, 19, 590522, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
    ]
