# Generated by Django 3.0.5 on 2020-04-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200421_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_type',
        ),
    ]
