# Generated by Django 3.0.5 on 2020-04-23 03:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_pizza_pizza_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(choices=[('S', 'Silican'), ('R', 'Regular')], default=datetime.datetime(2020, 4, 23, 3, 4, 32, 824785, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
    ]
