# Generated by Django 3.0.5 on 2020-04-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderplaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('sp_type', models.CharField(choices=[('S', 'Silican'), ('R', 'Regular')], max_length=1)),
                ('sp_price', models.DecimalField(decimal_places=2, help_text='price in US$', max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Orderplaced',
        ),
    ]
