# Generated by Django 3.0.5 on 2020-04-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200424_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SP',
        ),
    ]
