# Generated by Django 3.0.5 on 2020-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delete_sp'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderplaced',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=64)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order_status', models.CharField(choices=[('P', 'Order Placed'), ('C', 'In Kitchen'), ('L', 'Left for Deliver'), ('D', 'Delivered'), ('C', 'Cancelled')], default='P', max_length=1)),
            ],
        ),
    ]
