# Generated by Django 3.0.5 on 2020-04-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200425_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='user',
        ),
    ]
