# Generated by Django 3.0.5 on 2020-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200425_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='items_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
