# Generated by Django 3.0.5 on 2020-04-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderdata_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='order_items',
            field=models.CharField(max_length=143),
        ),
    ]
