# Generated by Django 3.0.5 on 2020-04-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200425_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderdata',
        ),
    ]
