# Generated by Django 3.0.5 on 2020-04-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_delete_orderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_items', models.CharField(max_length=143)),
                ('items_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
