# Generated by Django 3.0.5 on 2020-04-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderdata',
        ),
    ]
