# Generated by Django 3.0.5 on 2020-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_delete_orderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('items', models.CharField(blank=True, max_length=128)),
                ('items_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
