# Generated by Django 3.0.5 on 2020-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_status',
            field=models.CharField(choices=[('P', 'Order Placed'), ('D', 'Decesion Pending'), ('C', 'Completed')], default='D', max_length=1),
        ),
    ]
