# Generated by Django 3.0.5 on 2020-04-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200425_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_status',
            field=models.CharField(choices=[('Placed', 'Order Placed'), ('Not Placed', 'Not Placed'), ('Penging', 'Cooking'), ('Completed', 'Completed')], default='Not Placed', max_length=10),
        ),
    ]
