# Generated by Django 3.0.5 on 2020-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200426_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Not Placed', 'Not Placed'), ('Penging', 'Cooking'), ('Completed', 'Completed')], default='Not Placed', max_length=10),
        ),
    ]
