# Generated by Django 3.0.5 on 2020-04-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200426_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
